[package]
name = "parser"
edition = "2021"

[[bin]]
name = "decode_frames"
path = "bin/decode_frames.rs"

[[bin]]
name = "decode_key"
path = "bin/decode_key.rs"


[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
eyre = "0.6.12"
libdav1d-sys = "0.7.1"
pretty_assertions = "1.4.1"
